apiVersion: v1
kind: Secret
metadata:
    name: media-stack-api-keys
    namespace: media
type: Opaque
stringData:
    jellyseerr: ENC[AES256_GCM,data:3jvcBBc3etpw4B0+BbZqQzgoao4MzlpC/Nnp2EUXJ+T/eATOugPkYNsYV62uQ0+RHdVZ6yWc4VXgMHLWioq/fP6vqsw=,iv:tRpbEJeoa6lWlDB6zdT/GxPmQCgfGstJYst8Rj8ldqI=,tag:E8umxPE/+W5PeWy6+T8RRg==,type:str]
    prowlarr: ENC[AES256_GCM,data:ZA96YYlRI7jPDN3DCR7s2gmshVEe0HmJfXlLp+Arvq8=,iv:uzb6cVZnnrJj539g9HjqMDFhbqjvM9zVkPq+MJboOkg=,tag:37ajzZSk9Poqkw3SvQcCrA==,type:str]
    radarr: ENC[AES256_GCM,data:I5riHUsqtsb71aJXUHvdfK+cpk4seyJudRsgNwwLG+g=,iv:dvnjDLNAKwYpNMbOjlAGa+MxCwoBlVIZDKYqTCPbZm0=,tag:jINBbeJHtsK60kfJPeJEuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR3Bnbnl2cVhIMVRVTDhD
            NWI4bEtuaUZXaWdPYk5qYWZWVmljQ3ZzeTE4Cjlwd24vSmRQZHAvZHJxQ2FoblZB
            RG9zZmIyTFdmRUZMbmYvVGVmWndxcE0KLS0tIHVLcXFsWVZ3TStHZ1RSRXl0WUtB
            UGhNY1QrV2sydnRjejdkNStZcE5iNUEKxRQnKcKBJz30/m5gcK8ArN/gkcaNMtBQ
            QxqPAqLjcDozn4RQQ0SLXVdn0UbQzGKuEuVXqFN8c+fontAAh9j+zQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dseuugzmdrtpt7k7vuq5gvns2w678suy3z33up2lzr6xe787vewq3v45q5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T14:15:34Z"
    mac: ENC[AES256_GCM,data:BKBLbuTQ1HeZ4Cvnz5oE8Nl5QXTXFdlVJuzKyz3I05HkRmN9hAK3tF31VX6E9EkabbTL3S+bkwSA/Txqpegg97cG863DC8tO/uVDrdHY7A7T/2x6sbJzCMyWTXzvwo4JHauPBO/XCxXvPpEXfXiCoa8TTT+Z/piUuDQgJukzJmI=,iv:hxnF4JyIet6XT3irp+xF8hxV0IE25OsBAthNJW0/SIA=,tag:lO1cO2+jLyNxpnTYGra/lg==,type:str]
    version: 3.13.2
