defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 3
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 10
  upgradeChecker: false
  taintToleration: "node-role.kubernetes.io/control-plane=:NoSchedule"
persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  reclaimPolicy: Retain
csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 2
  snapshotterReplicaCount: 2

metrics:
  serviceMonitor:
    enabled: true
