apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: cloudflared
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:XoJX8bNaariFqidu+7mIynWQRb4BmLcdrKdckK6PFoZUQcgEJDuVTkH7pG3s7T/Xo7fTGJJsAs2BJh6sXWjQBRuISK6tG6PcHN5rBrRupIaxYiQCW8YZiOXk19eSOK8ZkSrX5jszJKKH0omMFDSYlJJoBQM3urSUUlOAIEUOXfI2ZlBAiEDwBD9WDo7RP87TfeCePulEoAUTMK+U6ik1qJIbcBJqVLpe6t7uyNIkzhebz+7ZXmkyxQ==,iv:xQGn/I60QCxKgyINS6YrhQGz/rugo3Dp8DaTSh5jtNw=,tag:XIavF13bBWKBC9U6r6YI8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSmNSOVNtUnE1ZjhwMktt
            aksrYnYrTU1RMlFNcjc5d1RlTUhTbnN4SmlVCkpzbWsrVDhYTXlsSXdGa2FPNGtR
            Ly9CNHp5WWFRdjQzbC9WQ0NnbVUxdk0KLS0tIElOU0xxYy9aU3g0aERicnEzVDA5
            bWg3a0xOMDNRVkt2OUswZWdWd29GR1kKZNjRdLBK09nLtrLlo7dR1p2mU93IVWrK
            QO1wmNjAPbWrA+/dRLbi/KIbIBjAI1vHooKzwjSIlfSwRGAjnrEP8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dseuugzmdrtpt7k7vuq5gvns2w678suy3z33up2lzr6xe787vewq3v45q5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T14:15:34Z"
    mac: ENC[AES256_GCM,data:NyVxgmGyFUqbMYtDQwCOM4qrzgfVSsF5SbOgp9+Hm5rBM/q8njNLP7u8eU0ULBMYalpkXsMZZ2NXJV07ar/yw1AwissYNkNkf96cgYNdKeQX+JAlV4nF0gMBuiKFEFdGE7FUyixy7XIpyfDFX2zHycS8sGHKuzyPFQpVDWjqauM=,iv:WyQLRqYqM+tvOEf7AJzr0AQij0PTWA8MF36U1+7ZGqY=,tag:zRzSPkH+w4Uw9bAMlcSuqg==,type:str]
    version: 3.13.2
