apiVersion: v1
kind: Secret
metadata:
    name: wireguard-admin
    namespace: wireguard
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:iJRageJKYfo4Pvdn0FYzonK7wkP8uaU=,iv:MowqQPwNBX9bS2LPnQbTn3F4+zeuyW3iWMeoAIwMJD8=,tag:Ywf3UtInE1uFsVmx3x5JnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd0UwTGsvczV1WnRVdkVr
            ZWYwU00zdUxEUEgrVytlaE5BYzRpaXczZ2dBCkNBUWxER0x2enlYSHhHa1ZwVllp
            R1k3d0duZHkxSkNXUzNvWmVnQzVNVncKLS0tIEVjM2ZKSnpyQkNjdWRWS2tvaGkv
            SkpQZ1Z4dzUvMnJTOU5TTGFVRFNTbFEK0CIirFZI4gGUnsbsrqKwDl+771MJb0zY
            QNoGKu3/I1a7jgYrvxhitcszLPf4smiSTzRC7YECoOvUoAE+L7kfVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dseuugzmdrtpt7k7vuq5gvns2w678suy3z33up2lzr6xe787vewq3v45q5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T14:44:41Z"
    mac: ENC[AES256_GCM,data:9Xsc70JkL66Br9aMNFlutZWIt1B7acJv/7sRo4MOnIi2y18ypZ4ggY3n5qr3BUB1po3ROl7A2/7WvRrz9fztw4OeVR+R0ABVAXDfQfy3uwkMPz0hQiciwHmu/mzQHDVx2X+VHBB2Wc/kpG3KvnIt4IO6n156pYRGcJIBB9DXVjY=,iv:MdyY3iS0IiSX1xKeWBy1NWsiMA3SzrWDL1OUtEltwwQ=,tag:wpKGG00NOk3zHnyCG313wA==,type:str]
    version: 3.13.3
