# Decrypt the SOPS-encrypted Talos secrets bundle authored at action time
# (cluster-bootstrap/talos/secrets.sops.yaml — generated by `talosctl gen secrets`
# then `sops --encrypt`). Keeping cluster identity in git means the cluster
# is reproducible from git + age key alone if TF state is lost.
data "sops_file" "talos_secrets" {
  source_file = "${path.module}/../talos/secrets.sops.yaml"
  input_type  = "yaml"
}

# Parse into the structure the Talos provider expects.
# `talosctl gen secrets` produces YAML with certs.os.{crt,key} etc; if a provider
# version produces schema validation errors, `terraform plan` will show the exact
# field mismatch — adjust this locals block accordingly.
locals {
  talos_machine_secrets = yamldecode(data.sops_file.talos_secrets.raw)

  talos_client_configuration = {
    ca_certificate     = local.talos_machine_secrets.certs.os.crt
    client_certificate = local.talos_machine_secrets.certs.os.crt
    client_key         = local.talos_machine_secrets.certs.os.key
  }
}
