# DESIGN: Non-standard secrets pattern — DO NOT refactor without revisiting.
#
# The official terraform-provider-talos example
# (siderolabs/contrib/examples/terraform/basic/main.tf) uses
#   resource "talos_machine_secrets" "this" {}
# which generates the cluster identity bundle into TF state.
#
# We deliberately diverge: cluster identity is generated once via
# `talosctl gen secrets`, SOPS-encrypted, and committed to git. Terraform
# decrypts it via data.sops_file. This preserves the "rebuild from age key
# alone" property called out in talos-cluster-PLATFORM.md — lose TF state
# and the workstation, no problem: re-clone the repo, decrypt with the age
# key, `terraform apply` rebuilds against the same cluster identity.
#
# Cost: the locals block below transforms talosctl's YAML field names
# (crt, bootstraptoken, secretboxencryptionsecret) into the provider's
# expected schema (cert, bootstrap_token, secretbox_encryption_secret).
# Without this transform the provider 0.11 fails with "missing required
# argument" on data.talos_machine_configuration.machine_secrets.

# Decrypt the SOPS-encrypted Talos secrets bundle authored at action time
# (cluster-bootstrap/talos/secrets.sops.yaml — generated by `talosctl gen secrets`
# then `sops --encrypt`). Keeping cluster identity in git means the cluster
# is reproducible from git + age key alone if TF state is lost.
data "sops_file" "talos_secrets" {
  source_file = "${path.module}/../talos/secrets.sops.yaml"
  input_type  = "yaml"
}

locals {
  _raw = yamldecode(data.sops_file.talos_secrets.raw)

  # Transform talosctl's YAML field names into terraform-provider-talos 0.11's schema.
  # The CLI writes:    certs.*.crt          secrets.bootstraptoken              secrets.secretboxencryptionsecret
  # The provider wants: certs.*.cert        secrets.bootstrap_token             secrets.secretbox_encryption_secret
  # Without this transform `data.talos_machine_configuration` errors with "missing required argument".
  talos_machine_secrets = {
    certs = {
      etcd = {
        cert = local._raw.certs.etcd.crt
        key  = local._raw.certs.etcd.key
      }
      k8s = {
        cert = local._raw.certs.k8s.crt
        key  = local._raw.certs.k8s.key
      }
      k8s_aggregator = {
        cert = local._raw.certs.k8s_aggregator.crt
        key  = local._raw.certs.k8s_aggregator.key
      }
      k8s_serviceaccount = {
        key = local._raw.certs.k8s_serviceaccount.key
      }
      os = {
        cert = local._raw.certs.os.crt
        key  = local._raw.certs.os.key
      }
    }
    cluster = {
      id     = local._raw.cluster.id
      secret = local._raw.cluster.secret
    }
    secrets = {
      bootstrap_token             = local._raw.secrets.bootstraptoken
      secretbox_encryption_secret = local._raw.secrets.secretboxencryptionsecret
    }
    trustdinfo = {
      token = local._raw.trustdinfo.token
    }
  }

  # talosctl client auth for `apply` / `bootstrap` gRPC calls.
  talos_client_configuration = {
    ca_certificate     = local._raw.certs.os.crt
    client_certificate = local._raw.certs.os.crt
    client_key         = local._raw.certs.os.key
  }
}
