apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:05SErbnMk8euXxRfNKgnFqSLfkOGoqLCMiPQnXJIq8xYYt9JFPfqz+zcIOHzXrln,iv:6iW02zIsGxdwyMP5vjhWi/tsC4OFy3ttylob2tEs7KQ=,tag:Z1Sm+4WSFEB/IBzzQ1C2hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc0JaTVdRNnJVOGlXWEhP
            NVIvay9mVUpud2g1ZkZabXVZYm5YaXYySjI4ClZvSktKVy95TE41QW9FM3IvZEpQ
            dG9GdkpKWUNMNVdseWowV21pS2xyYWsKLS0tIGpwVzY4MlZkTVBuK0RUN1pZWHlB
            Q3lkaVpkczd5Y2o0aU5zeklDWDRJNjgKsAlk6uvgxNCPC1WKkmjEGFPrmK78hlSb
            acapNNhoRrfpfqVChEEJx9OYFG2NUitO4+I4Mz2RZg7mcfDfn77QIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dseuugzmdrtpt7k7vuq5gvns2w678suy3z33up2lzr6xe787vewq3v45q5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T14:15:34Z"
    mac: ENC[AES256_GCM,data:HXGrdaQiun9dL+cj8ep3crV3GSnYWSkvq3cpq2mDUpDuohXS615eFpdvZ5/Zl0G0CRutaVzliWdldmYEjMb6rYMs+7JXIJP4iST6wCaPjktrrEj5+0SRxfadvAt4b3M9ls02OprCI75gBBhLzO4OI8dnXgMSYh6ntkxuARKgX7g=,iv:uZZ28Eyh6CNtItkaRi2Jw8/95EHPEfEG1RSW5Hu/CF0=,tag:rBBU6hzULCDwe9MCFSS/FA==,type:str]
    version: 3.13.2
