apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Xmve/5wErz4wN3VLRqmLGEJIuj+GWIaSVVMRXWqeIm/dnsDn9UMEJbroQhbK/xOt,iv:3d/kc1N+omUzL4uxbkbZhkeA9RzHjNboLROPjGmMGT0=,tag:MCsNiJK3/tlfp6Thqp01og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN1ZYdi9iV0RLSk9uUUF3
            SGpHMEFIQTJLc0FVazBPZWxkRHhWZnpkVkdnCngraW1QQkpGa2EvOVhFZ0I5TnRu
            R2lmMm5HVU03THByTXRKUTRqVGVFR0UKLS0tIGdDcWRKd0Nld1FySUc0Vm5veDZm
            YjJmWTNqTFprQ0dGOGdQNUJXTHBkQ28Kx+CLQfwIj60Llmoid4Qih0WfWD15dt8x
            uSrxeE6BguIJkrqdlMaPcOtu2dRZnypO5i0PiLKDTG8feBJqTI5QQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dseuugzmdrtpt7k7vuq5gvns2w678suy3z33up2lzr6xe787vewq3v45q5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T15:17:25Z"
    mac: ENC[AES256_GCM,data:XGw1S05VAmMmVAgu7uWA14i6NALqDHdaFu77796WhucwNdFe/rtjOAK1IFcVxii63Sw9JbNV8sldJC1s3Djyp8KuR/ErOXeH9RDrrHn194jIWqg5ULqWEiDOPpZEQgjwggRn1iNZWGdgWyzjOKqkYS7wgCOe8kCgwtsbvivyKQ0=,iv:h0fIuEQ/HVMLSea1qiWzH6LfThEPXnyRC1nuOJVyvMo=,tag:Yir1K4n6tpv216NBtT+tiQ==,type:str]
    version: 3.13.2
