apiVersion: v1
kind: Secret
metadata:
    name: smee-config
    namespace: flux-system
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:SOlGLRUJ46HDf5WlUQOnboEVuuQ/YEBLKzMRpJMPpA==,iv:ly5Ov0WDVgS+EN3QU5J+iVS1vx6f66Fnq2R+ZIH4FOA=,tag:ZK7Tko1a6GUXu+ecypMQjg==,type:str]
    path: ENC[AES256_GCM,data:ET0MFwfviUIcOao2kbkoQg5he0nqjYzCeQ==,iv:9tOfZrSAP+wabqyPqMvZL0fP7JGgao5Vk21c+pXIdJY=,tag:79MkbFalq4ucA7cEXkTAoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVHVkSjR5T29zS1NlRDRI
            SmdqMGUvNnk2ZG05d1gwNDFYNXBMNnFXa2lnCkdINDlhTXNVRWx1T2l1MmRNWFlx
            Y0FkeGphSlRLYmEvOGpNQ2NyNlhyNFkKLS0tIDVRQlZQbUNkQ3hXNCtvcjAvbGls
            Q1c5NnJJR3hpWUdjRjg3SiswT1Ixc00KJYsNaf2kqsLQCeAe1l1nOASA+Ym4XvOQ
            jKrTjKn7U/g0Qv1Qv7WzqGfW+DueqKzUEmQxy7ZVllHQa1hrOxATPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dseuugzmdrtpt7k7vuq5gvns2w678suy3z33up2lzr6xe787vewq3v45q5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T14:15:34Z"
    mac: ENC[AES256_GCM,data:Rlv848nVrtpMyxsDGLy9DlUuPCgewu22CQ6WxCSQjPj6jrewvv4dA+cCY92+UsnN7Lz9Bk2vRiKEnX/guHlY9qdMfnkMPfvHSKNt81LiMfsNnz63Vmlc77nYJ9IkOHybmcR5BWwfVfxtFZVyaZticY1v8Hju1gUQGJluZ8hKx+c=,iv:pc4efJkyaAZZJ5igKS89kd/X9CHwuiKvB8BcgxIYa68=,tag:AZtqMnd7WP4I79finvwOYg==,type:str]
    version: 3.13.2
