apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
data:
  recyclarr.yml: |
    radarr:
      main:
        base_url: http://radarr.media.svc.cluster.local:7878
        api_key: !env_var RADARR_API_KEY
        delete_old_custom_formats: true

        quality_definition:
          type: movie

        quality_profiles:
          - trash_id: d1d67249d3890e49bc12e275d989a7e9  # HD Bluray + WEB
            reset_unmatched_scores:
              enabled: true
