apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:7YH1mbn/xHxQO1L76VSWkV8lUud/mPKzU6HH6J64IJo=,iv:v2saiQZvSharVwacxM9UOG3tr74zC1zFW0SlGI21EVs=,tag:js3ksgvbr0LXv9DFdxIUAg==,type:str]
    admin-user: ENC[AES256_GCM,data:f+zv8K8=,iv:6XoniNLNgDT/FoxONs10fQuVTw8rS14HldgVwJyfUdc=,tag:dxboSb9H/+Pl5m61MG9+Uw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdno4b3o4ZmJEeXVUMW5D
            VHVBcHVxME1NWG1lcWhkUU5rQ0xqS1p2RkNBClU1L0NWUklIT3kyb01CaFg2eFd1
            RVl2azMwTFZjUnJwOE1TWkgxUUNyOHcKLS0tIFdFM015UzJWMVgzUGlkTS9qZG1v
            TFpTdEs2VEU1WmhZY0FFUXVlTVlvMEUKF96Itdger+/mx2M2+QrGcofFlrmwFHq4
            A/sRlb3i1REuEgWksYaMJ+SeQhuRmP2vp6+Gyo6cLLgBPmrwGXNlcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dseuugzmdrtpt7k7vuq5gvns2w678suy3z33up2lzr6xe787vewq3v45q5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T14:15:34Z"
    mac: ENC[AES256_GCM,data:njenrOWASs1MokEx1ahu2WAoKFPatgBvD2zEvlWJa4WOAsTCeszfgPz5ffK7Hc+SM16hdQnjK40R50h1OU2bLvrSyxsvZyqcxk9h5OpEtZrcJNgWGD2ZA8kao0742VidT0EawsaqIuRgY71A62Ud/Hu2WfQ/h4Yu59enhUlMmcE=,iv:rsSitX0BJtMBvPpTGEa7T54bmEkzkgd5DDKbPhhnkYQ=,tag:Dlx3tJc9ARmx82gtjzfBEw==,type:str]
    version: 3.13.2
