fullnameOverride: vm

vmcluster:
  enabled: false

vmsingle:
  enabled: true
  spec:
    retentionPeriod: "30d"
    storage:
      accessModes: [ReadWriteOnce]
      storageClassName: longhorn
      resources:
        requests:
          storage: 20Gi
    extraArgs:
      maxLabelsPerTimeseries: "40"

vmagent:
  enabled: true
  spec:
    selectAllByDefault: true
    scrapeInterval: 30s

vmalert:
  enabled: true
  spec:
    evaluationInterval: 30s
alertmanager:
  enabled: true
  spec:
    replicaCount: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          storageClassName: longhorn
          resources:
            requests:
              storage: 1Gi

kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false

defaultRules:
  create: true
grafana:
  enabled: false
